#! /bin/sh

sxhkd &
redshift -P -O 4600k &

external_monitor_connected=$(xrandr -q | grep 'HDMI-1-0' | cut -d " " -f 2)
if [[ $external_monitor_connected == "connected" ]]; then
    xrandr --output 'eDP-1' --primary --mode 1920x1080 --rotate normal --output 'HDMI-1-0' --mode 1920x1080 --rotate normal --rate 75 --left-of 'eDP-1'
    bspc monitor 'HDMI-1-0' -d 1 2 3 4 5 6 7 
    bspc monitor 'eDP-1' -d 8 9 0 
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc rule -a Slack desktop='^8'
bspc rule -a TelegramDesktop desktop='^8'
bspc rule -a Brave-browser desktop='^2'

bspc config border_width        0 
bspc config window_gap          6
bspc config border_radius       3
bspc config top_padding 	 	20
bspc config bottom_padding      0
bspc config left_padding 	 	0
bspc config right_padding 	 	0

bspc config normal_border_color	 "#4c566a"
bspc config active_border_color	 "#1e1e1e"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color"#5e81ac"
bspc config urgent_border_color  "#dd2727"

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#wallpaper
feh --bg-fill /home/metal/Pictures/Wallpapers/154.jpg

#Compositor  
xrdb $HOME/.Xdefaults
$HOME/.config/polybar/launch.sh 
