" Belongs to github.com/bojle
" do whatever you want with it

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

" Load Plugins
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'justinmk/vim-sneak'
"Plug 'elixir-editors/vim-elixir'
Plug 'petRUShka/vim-opencl'
Plug 'neovimhaskell/haskell-vim'
Plug 'vhda/verilog_systemverilog.vim'
call plug#end()

""" Vim Native Plugins
packadd! matchit
runtime macros/matchit.vim
runtime! ftplugin/man.vim

" change colorscheme
colorscheme gruvbox
set background=dark

""" turn indentation on
filetype plugin indent on

""" autocmds
autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType python setlocal shiftwidth=4 softtabstop=4
autocmd FileType *.hs setlocal tabstop=4 shiftwidth=4 expandtab=4
autocmd FileType text,markdown,tex,rst setlocal spell spelllang=en_gb
autocmd FileType text,markdown,tex,rst set textwidth=80
autocmd FileType c,cpp setlocal equalprg=clang-format\ --style=LLVM
autocmd FileType gitcommit set textwidth=72
autocmd FileType gitcommit set colorcolumn=73

""" set options
set tabstop=2
set shiftwidth=2
set expandtab
set number
set relativenumber 
set cursorline
set smartcase
set ignorecase
set nocompatible
set laststatus=2
set complete+=kspell
set showcmd
set lazyredraw
set path=**
set wildmenu
set autoread
set hlsearch
set splitright
set splitbelow
set esckeys
set complete-=i

set makeprg=make\ -j\ 6

" Abbreviations
cabbrev h vert bo h
cabbrev tn tabnew

""" maps
noremap <leader><space> :nohlsearch<CR>
nnoremap <Esc>E :!chmod +x % && ./%<CR>
nnoremap <Esc>P :!mdtopdf -d %<CR>
nnoremap ]q :cnext<CR>
nnoremap [q :cprevious<CR>
nnoremap <leader>r :!ctags -R<CR>
map <space> <leader>

""" Commands
command Dgt execute "vert bo help digraph-table"
command Vt execute "vertical terminal"

""" Source Code Navigation
nnoremap <leader>d :Rg<CR>
nnoremap <leader>f :Files<CR>

"inoremap <A-I> <Esc>:m .+1<CR>==gi
"inoremap <A-O>  <Esc>:m .-2<CR>==gi
"nnoremap <A-I> :m .+1<CR>==
"nnoremap <A-O> :m .-2<CR>==

let g:ft_man_open_mode = 'vert'

""" haskell

let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords

" For verilator error messages of the form:
" %Warning-UNUSEDSIGNAL: rtl/ibuf.v:128:36: Bits of signal are not used: 'a'[31:16]
set efm+=%%Warning-WIDTHEXPAND:\ %f:%l:%c:\ %m
