" Belongs to github.com/bojle
" do whatever you want with it

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

" Load Plugins
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'justinmk/vim-sneak'
call plug#end()
packadd! matchit
runtime! ftplugin/man.vim

" change colorscheme
colorscheme gruvbox
set background=dark

""" turn indentation on
filetype plugin indent on

""" autocmds
autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType python setlocal shiftwidth=4 softtabstop=4
autocmd FileType text,markdown,tex setlocal spell spelllang=en_gb
autocmd FileType text,markdown,tex set textwidth=80

""" set options
set tabstop=4
set shiftwidth=4
set number
set relativenumber 
set cursorline
set smartcase
set nocompatible
set laststatus=2
set complete+=kspell
set showcmd
set lazyredraw
set path=**
set wildmenu
set autoread
set hlsearch
set splitright
set splitbelow
set esckeys


" Abbreviations
cabbrev h vert bo h
cabbrev tn tabnew

""" maps
noremap <leader><space> :nohlsearch<CR>
nnoremap <Esc>E :!chmod +x % && ./%	
nnoremap <Esc>P :!mdtopdf -d %
nnoremap ]q :cnext<CR>
nnoremap [q :cprevious<CR>

map <leader>* :grep <cword> * --exclude-dir={.git,tmp,log}<CR><CR>

command Dgt execute "vert bo help digraph-table"

""" Plugin specific options

nnoremap <leader>d :Rg<CR>
nnoremap <leader>f :Files<CR>

let g:ft_man_open_mode = 'vert'

map <space> <leader>
