#!/usr/bin/env bash

count=0
disconnected="󰖪 "
wireless_connected="󰖩 "
ethernet_connected="󰈀 "

# check where packets are being routed through
# depending on interface state being UP/DOWN is not reliable
# as both interface can be up at the same time
while true; do
    output="$(ip route get 8.8.8.8)"
    if (ping -c 1 google.com) &>/dev/null; then
        if [[ "$output" =~ enp ]]; then
            echo "$ethernet_connected" ; sleep 2
        elif [[ "$output" =~ wlp ]]; then
            echo "$wireless_connected" ; sleep 2
        fi
    else
        echo "$disconnected" ; sleep 0.5
    fi
done
